export const SET_INITIAL_DATA = 'SET_INITIAL_DATA';
export const SET_INITIAL_DATA_START = 'SET_INITIAL_DATA_START';
export const SET_INITIAL_DATA_SUCCESS = 'SET_INITIAL_DATA_SUCCESS';
export const SET_INITIAL_DATA_FAIL = 'SET_INITIAL_DATA_FAIL';

export const FETCH_WEATHER_DATA = 'FETCH_WEATHER_DATA';
export const FETCH_WEATHER_DATA_START = 'FETCH_WEATHER_DATA_START';
export const FETCH_WEATHER_DATA_SUCCESS = 'FETCH_WEATHER_DATA_SUCCESS';
export const FETCH_WEATHER_DATA_FAIL = 'FETCH_WEATHER_DATA_FAIL';

export const AUTH_HANDLER = 'AUTH_HANDLER';
export const AUTH_HANDLER_START = 'AUTH_HANDLER_START';
export const AUTH_HANDLER_SUCCESS = 'AUTH_HANDLER_SUCCESS';
export const AUTH_HANDLER_FAIL = 'AUTH_HANDLER_FAIL';

export const LOG_OUT_HANDLER = 'LOG_OUT_HANDLER';

export const SAVE_DATA_HANDLER = 'SAVE_DATA_HANDLER';

export const FETCH_DATA_TO_REDUX_SUCCESS = 'SAVE_DATA_HANDLER_SUCCESS';
export const FETCH_DATA_TO_REDUX_FAIL = 'FETCH_DATA_TO_REDUX_FAIL';

export const GET_CITY_DATA = 'GET_CITY_DATA';
export const GET_CITY_DATA_START = 'GET_CITY_DATA_START';
export const GET_CITY_DATA_SUCCESS = 'GET_CITY_DATA_SUCCESS';
export const GET_CITY_DATA_FAIL = 'GET_CITY_DATA_FAIL';

export const REMOVE_CITY_DATA = 'REMOVE_CITY_DATA';

